- index.html
- styles.css
- Added smooth animations.
- Improved button and link hover states.
- Enhanced layout with shadows and gradients.
> feat: enhanced the css file with animation

- index.html
changed the tagline in html code
> feat: changes to tagline in html code

- index.html
> feat: changes a html para

- index.html
> feat: changes made

- index.html
> feat: change inside the header

- index.html
- styles.css
Add Navbar in index.html file and styles.css file
> Feat Add NavBar

- about.html
- aboutscript.js
- aboutstyle.css
- homestays.css
- homestays.html
- homestays.js
- index.html
- script.js
- style.css
1. Created Homestays Page
2. Fixed Chat button
3. added back to top button
> feat: Added Homestays Page

- services.html
- servicesscript.js
- servicesstyle.css
> service page

- about.html
- contact.html
- faq.html
- homestays.html
- index.html
- login.css
- login.html
- login.js
- pp.html
- services.html
- t&c.html
Here I added the log in page using **html**, **css** and **javascript**.
> Feat: Making the log in page  

- about.css
- contact.css
- contact.html
- contact.js
- faq.css
- faq.html
- faq.js
- homestays.css
- homestays.html
- homestays.js
- pp.css
- pp.html
- pp.js
- script.js
- services.html
- servicesscript.js
- servicesstyle.css
- t&c.css
- t&c.html
- t&c.js
> feat: Added Chatbot to all pages

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
closes #66 
I have added Issue and PR template
> Added issue and pr template

- README.md
Title : ReadME Doc Tweak
Closes #85
- Adding some more emojis where they where omitted
- Grammar tweak
> ReadMe doc Tweak

- .vscode/settings.json
- CSS/about.css
- CSS/contact.css
- CSS/faq.css
- CSS/homestays.css
- CSS/pp.css
- CSS/servicesstyle.css
- CSS/style.css
- CSS/t&c.css
Title : improved hover effect in social icons
Closes #65 
improved hover effect in social icons
> improved hover effect in footer icons

- CSS/servicesstyle.css
- JS/servicesscript.js
- services.html
#91 
Title :Update Service Page
Closes #91 
1. added 5 tabbed section 
2. added homestay booking section
3. added bus service booking section
4. added workshop
5. added local experience
6. add holiday packages
Rural Retreats Only
> feat: Updated ServicePage

- about.html
- contact.html
- faq.html
- homestays.html
- index.html
- services.html
Enhances the website’s SEO performance by adding essential meta tags to improve search engine rankings and social media previews. 
Fixes : #102 
- Added meta tags for title, description, and keywords to improve search engine discoverability.
- Included Open Graph (OG) meta tags for better previews on Facebook and LinkedIn.
- Added Twitter Card meta tags for optimized Twitter previews.
- Ensured consistency across all .html files for SEO best practices.
**Screenshots:**
> Added essential meta tags for SEO optimization

- CSS/about.css
- CSS/faq.css
- CSS/homestays.css
- CSS/pp.css
- CSS/servicesstyle.css
- CSS/style.css
- CSS/t&c.css
- JS/script.js
- index.html
#106 
Title : Blog Section - Update and Enhance it
Closes #106 
Updated blog section 
only rural retreats
> feat: Updated Blog Section

- Adventure.html
- CSS/Adventure.css
- JS/Adventure.js
#113 
Title : Update Adventure Webpage fully
Closes  #113  
add new cards, style, functions
Rural Retreats only
> feat: Updated Adventure Page

- CSS/homestays.css
- homestays.html
Title : Improved Filter Section 
Closes #116
This PR enhances the filter section by:
Adding smooth transitions and glassmorphism effects to dropdowns.
Improving the 3D effect on the "Apply Filter" button.
Adjusting styling to maintain a modern and clean UI.
Making the heading more appealing.
Improving the entire look of the filter section under homestays page.
Rearranging the filters to give it a cleaner look.
Before :
After improvement:
https://github.com/user-attachments/assets/8b7009b8-5f6a-41d7-b65e-24c832facb37
**Additional context(if any)**
APERTRE 2025
> feat: Improved filter section 

- CSS/blog.css
- JS/about.js
- JS/blog.js
- JS/contact.js
- JS/faq.js
- JS/homestays.js
- JS/pp.js
- JS/script.js
- JS/servicesscript.js
- JS/t&c.js
- blog.html
#115 
Title : Update Blog Webpage fully 
Closes #<issue_no>
#115 
Update Blog Webpage fully 
1. added images 
2. added navbar
3. added footer
4. enhanced the css file
5. more detailed html structure
Rural Retreats only
> feat: Updated Blog Webpage

- Adventure.html
- CSS/Adventure.css
Closes #120   
- Enhanced UI of the footer with consistent colors and improved styling.
- Changes made in Adventure.css and Adventure.html.
-  Updated `<link rel="stylesheet" href="../CSS/Adventure.css">` to `<link rel="stylesheet" href="./CSS/Adventure.css">` in Adventure.html to correctly apply styles.
- Updated Font: Changed the font from **Poppins** to **Raleway** for a more refined look.
- Subtitle Color Update: Adjusted the **subtitle color** for better readability.
- Subscribe Text Color Change: Changed the Subscribe text color from **white** to **#132441** for improved visibility.
- Social Icons Hover Effect: Modified the **hover color** of social icons to enhance visual consistency.
Before changes:
After Changes:
Contributing under Apertre 2.0 
<<<<<<< HEAD
=======
>>>>>>> …
> enhance footer

- Budget.html
- CSS/Budget.css
Closes #129  
<<<<<<< HEAD
=======
> Changes made 

- CSS/homestays.css
- CSS/style.css
- index.html
Closes #137 
<<<<<<< HEAD
=======
> Changes the traveller section

- CSS/homestays.css
- CSS/style.css
- index.html
Closes #138 
<<<<<<< HEAD
=======
> Changes the footer section information

- .vscode/settings.json
- CSS/about.css
- CSS/blog.css
- CSS/contact.css
- CSS/faq.css
- CSS/homestays.css
- CSS/pp.css
- CSS/servicesstyle.css
- CSS/style.css
- CSS/t&c.css
- CSS/travelSustain.css
- blog.html
- contact.html
- faq.html
- homestays.html
- index.html
- pp.html
- services.html
- t&c.html
Closes #136 
<<<<<<< HEAD
=======
> Made the modification

- CSS/about.css
- CSS/homestays.css
- CSS/style.css
Closes #169
<<<<<<< HEAD
=======
> Update the location section

- CSS/contact.css
- CSS/homestays.css
Closes #163
<<<<<<< HEAD
=======
> Update the contact section

- CSS/homestays.css
Closes #155  
<<<<<<< HEAD
=======
> Update the explore more

- CSS/style.css
Closes #154
<<<<<<< HEAD
=======
> Changes the learn more button

- CSS/contact.css
- CSS/faq.css
- CSS/homestays.css
- CSS/servicesstyle.css
- homestays.html
Closes #168 
<<<<<<< HEAD
=======
> Enhance the faq section

- CSS/blog.css
- CSS/servicesstyle.css
- CSS/style.css
Closes #158  
<<<<<<< HEAD
=======
> Add effects to subscribe

- CSS/servicesstyle.css
> Change the service section

- CSS/servicesstyle.css
- CSS/style.css
Issue : #160  
Closes #<issue_no>  
<<<<<<< HEAD
=======
> Add effects to social links

- CSS/style.css
Closes #200
<<<<<<< HEAD
=======
> Fix the traveler section

- CSS/homestays.css
Closes #207
<<<<<<< HEAD
=======
> Update the homestay section

- CSS/homestays.css
Closes #206  
<<<<<<< HEAD
=======
> Update the booking

- CSS/homestays.css
Closes #205
<<<<<<< HEAD
=======
> Update the button

- CSS/splash.css
- JS/splash.js
- index.html
Closes #220  
Added Splash Screen with animation effects 
- [✅] My code follows the project's coding style.  
- [✅] I have tested my changes thoroughly.  
- [✅] Necessary documentation updates have been made.
> feat:Added Splash Screen

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Closes #209  
Corrected & Updated the PULL REQUEST TEMPLATE and FEATURE REQUEST TEMPLATE 
- [✅] My code follows the project's coding style.  
- [✅] I have tested my changes thoroughly.  
- [✅] Necessary documentation updates have been made.
> feat:Corrected & Updated the PULL REQUEST TEMPLATE

- CSS/about.css
- CSS/contact.css
- CSS/faq.css
- CSS/homestays.css
- CSS/pp.css
- CSS/servicesstyle.css
- CSS/style.css
- CSS/t&c.css
- about.html
> Footer Fix

- JS/script.js
- JS/splash.js
Closes #230 
The time delay between  the loading screen and the time to start the scroll has been matched
https://github.com/user-attachments/assets/165a7c7b-bfa1-41f0-b963-3d182713945b
Apertre 2.0 
<<<<<<< HEAD
Apertre 2.0
=======
> Fixed the time delay in the loading

- CSS/homestays.css
- homestays.html
Closes #233
---
---
---
---
---
Program Name: 
---
> Enhance the homestays page

- CSS/blog.css
- CSS/style.css
Closes #<issue_no>  
<<<<<<< HEAD
=======
> Update the blog section

- CSS/style.css
Closes #246  
---
---
---
---
---
Program Name: 
---
> Update the blog

- CSS/style.css
- index.html
Closes #251
---
---
---
---
---
Program Name: 
---
> Update the section

- CSS/style.css
Closes #249 
---
---
---
---
---
Program Name: 
---
> Update the explore section

- CSS/style.css
Closes: #250 
---
---
---
---
---
Program Name: 
---
> Update the explore our destination section

- CSS/style.css
Closes: #217 
---
- What issue does this fix? UI of Testimonial Section of Home page
- What major changes were made? Just fixed the display property
---
---
---
Fixes: #217 
---
Program Name: 
Yes, Under Apertre 2.0
---
> Fixed Testimonial Section

- CSS/style.css
- index.html
Closes #269 — UI improvement contribution
---
This PR enhances the Latest Articles buttons on the homepage:
- Added hover glow effect for interactive feedback
- Added subtle pop (scale) effect on hover
- Improved padding and spacing for a cleaner layout
These changes improve the visual design and interactivity of the buttons.
---
---
---
None
---
Program Name: Open Source Connect India - 2025
---
This contribution focuses solely on UI improvements for the Latest Articles buttons.  
- Hover effects with glow and pop to enhance interactivity.  
- Button padding and spacing were adjusted for a cleaner layout.
- No functional changes were made.
> style: enhance Latest Articles buttons with hover glow and pop effect.

- services.html
Community Building Icon is added.
---
---
- ✅  My code follows the project's coding conventions  
- ✅ I have tested all impacted features  
- ✅I have updated or added necessary documentation  
---
Program Name: OSCI (Open Source Connect India)
---
> Community Building Icon Added

- index.html
✅ Summary of Changes:
Added relevant meta tags (description, keywords, viewport) across all HTML files
Improved heading structure for semantic clarity (<h1> to <h3> hierarchy)
Ensured all images include descriptive alt attributes
Linked canonical URLs to prevent duplicate indexing
Optimized title tags for clarity and keyword relevance
Verified proper use of <meta charset="UTF-8"> and <meta name="robots">
---
> SEO Enhancements for RuRal-ReTreats

- JS/contact.js
- contact.html
Closes #<issue_number>  
closes #311 
---
It allows user to allow valid 10 digit phone number.
I added a validatePhone() function to check whether the phone number entered by the user is a 10-digit number or not.
---
Before -
After - 
---
---
#311 
---
Program Name: 
OSCI'25
---
> FIX : Phone number validation done

- Adventure.html
- Budget.html
- CSS/Adventure.css
- CSS/Budget.css
- CSS/about.css
- CSS/blog.css
- CSS/contact.css
- CSS/faq.css
- CSS/homestays.css
- CSS/pp.css
- CSS/servicesstyle.css
- CSS/style.css
- CSS/t&c.css
- about.html
- blog.html
- contact.html
- faq.html
- homestays.html
- index.html
- pp.html
- services.html
- t&c.html
- ts.html
Closes #397 
---
- What issue does this fix? 
Changed the footer styling of the website to make it look cleaner and more modern.
The newsletter section input and buttons have been integrated as a single component and the social media icons have been changed into a rounded look to make it look cleaner.
---
---
---
#397 
---
OSCI'25
---
Please review and merge
> Change Footer styling of the Website

- about.html
Added Video with responsive auto-play.
---
---
-  ✅My code follows the project's coding conventions  
-  ✅I have tested all impacted features  
-  ✅I have updated or added necessary documentation  
---
Program Name: Open Source Connect India (OSCI)
---
> Video Added with auto-play

- CSS/about.css
- CSS/contact.css
- CSS/faq.css
- CSS/homestays.css
- CSS/servicesstyle.css
- contact.html
- faq.html
- homestays.html
- index.html
- services.html
Closes #428 
I have enhanced the navbar by shifting the logo on the left side and hamburger bar on thr rigt and the login button inside the hamburger bar in mobile mode.
And this change i have made for all the pages.
---
I am contributing under OSCI
> Enhanced the navbar (login button inside the hamburger bar)

- JS/script.js
(https://github.com/Nayanika1402/RuRal-ReTreats/issues/449)
Closes #449 >  
---
Problem:
The chat-bot was not displaying any answers on initial load. When users asked questions, they received no responses or got generic "I don't know" messages. 
Troubleshooting:
Initial Investigation: Discovered the issue was related to data initialisation timing and variable scoping
Attempted Fixes:
Tried fixing data fallback logic and removing || answers patterns
Moved chatbot functions inside DOMContentLoaded to resolve scope issues
Created debug versions to trace data flow and identify where answers were getting lost
Tested multiple data initialisation approaches to ensure window.chatbotData was properly set
Root Cause:
Inconsistent data loading between initial chatbot load and post-clear state
Final …
> Fixed The Chatbot Not Answering The Pre-Set Questions Which Appear When You Click The Bot

- homestays.html
- Updated `homestays.html` with **unique homestay details** (square feets, , amenities).
- Removed repetitive content to improve **user experience**.
- Ensured the **map filter section** and **booking form** remain unchanged as in original.
- Enhanced readability and structure for better presentation.
- The original file had **duplicate homestay entries**, which reduced clarity.
- By making each homestay unique, it provides more **value to end-users** and aligns with project goals.
- This change makes the UI content more **realistic, professional, and user-friendly**.
- No breaking changes — existing functionality like **map filter, booking form, footer, chatbot** works as before.
- Content improvements make the website **more engaging and usable**.
🏅  contributing under an open-source …
> Fix: Improved homestay listings with unique details and better readability

- package-lock.json
- village.html
check @Nayanika1402 
Issue no #495
> improve in card

- about.html
- contact.html
- faq.html
- index.html
- login.html
- pp.html
- t&c.html
Closes #503 
- **What issue does this fix?** Fixed favicon 404 errors caused by mismatched filename references across multiple HTML files
- **What major changes were made?** 
- Corrected favicon file references from underscores (`favicon_16x16.png`) to hyphens (`favicon-16x16.png`) to match actual filenames
- Updated 7 HTML files: `index.html`, `contact.html`, `about.html`, `faq.html`, `t&c.html`, `login.html`, and `pp.html`
- Fixed both favicon links and JSON-LD structured data references
---
- Related to website performance and user experience improvements
---
Program Name: OSCI'25 (Open Source Contribution Initiative 2025)
---
This fix eliminates 404 errors in browser console and ensures proper favicon display across all website pages. All favicon files in the `/favicon/` directory use …
> Fix favicon references by replacing underscores with hyphens across all HTML files
